-- MySQL Script generated by MySQL Workbench
-- Wed Sep 24 08:48:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema tenderhub
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tenderhub` ;

-- -----------------------------------------------------
-- Schema tenderhub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tenderhub` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `tenderhub` ;

-- -----------------------------------------------------
-- Table `latest_tenders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `latest_tenders` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `latest_tenders` (
  `no_` INT NOT NULL AUTO_INCREMENT,
  `ref` VARCHAR(10) NULL DEFAULT NULL,
  `title` VARCHAR(200) NOT NULL,
  `sector` VARCHAR(100) NULL DEFAULT NULL,
  `value_` DECIMAL(15,2) NOT NULL,
  `closing` DATETIME NOT NULL,
  `status_` ENUM('open', 'closed', 'awarded') NULL DEFAULT 'open',
  `established` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`no_`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ref` ON `latest_tenders` (`ref` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `new_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `new_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `new_user` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(150) NOT NULL,
  `license_no` VARCHAR(100) NOT NULL,
  `e_mail` VARCHAR(150) NOT NULL,
  `password_` VARCHAR(10) NOT NULL,
  `confirm_password` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `company_id` ON `new_user` (`company_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `company_name` ON `new_user` (`company_name` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `license_no` ON `new_user` (`license_no` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `e_mail` ON `new_user` (`e_mail` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `staff` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `staff` (
  `employee_id` INT NOT NULL,
  `password_` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `employee_id` ON `staff` (`employee_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NULL DEFAULT NULL,
  `password_` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `new_user` (`company_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `user_id` ON `users` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `company_id` ON `users` (`company_id` ASC) VISIBLE;

SHOW WARNINGS;
USE `tenderhub`;

DELIMITER $$

USE `tenderhub`$$
DROP TRIGGER IF EXISTS `trg_latest_tenders_no_` $$
SHOW WARNINGS$$
USE `tenderhub`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `tenderhub`.`trg_latest_tenders_no_`
BEFORE INSERT ON `tenderhub`.`latest_tenders`
FOR EACH ROW
BEGIN
  SET NEW.ref = CONCAT('TH-', LPAD((SELECT IFNULL(MAX(no_),0) + 1 FROM latest_tenders), 5, '0'));
END$$

SHOW WARNINGS$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
